-- Q17: Vay Nhanh disbursement Mar 1-5 2026
SELECT
  DISBURSED_DATE,
  COUNT(*) as loan_count,
  COUNT(DISTINCT AGENT_ID) as unique_borrowers,
  SUM(LOAN_AMOUNT) as total_disbursed
FROM `momovn-prod.BU_FI.BAOTU_VAYNHANH_LOAN_INFO`
WHERE DISBURSED_DATE BETWEEN '2026-03-01' AND '2026-03-05'
GROUP BY DISBURSED_DATE
ORDER BY DISBURSED_DATE
