SELECT TYPEID, COUNT(*) AS orders, ROUND(SUM(FINAL_REV)/1e6,1) AS rev_M
FROM `momovn-prod.BU_FI.att_fi_ins_nl_ver2`
WHERE CC_STATUS='SUCCESS'
  AND SP='Vehicle Ins'
  AND TRANS_DATE BETWEEN '2026-01-01' AND '2026-01-31'
  AND TYPEID IS NOT NULL
  AND TYPEID != ''
GROUP BY 1
ORDER BY orders DESC
LIMIT 10
