-- Q20: CLO new contracts + revenue, Jan/Feb 2026 vs Jan/Feb 2025

-- Part 1: Disbursement by month (use DATE_MODIFIED for status tracking)
SELECT
  DATE_TRUNC(DATE_MODIFIED, MONTH) AS month,
  COUNT(DISTINCT TICKET_ID) AS contract_count,
  SUM(CONTRACT_AMOUNT) AS disbursement_amount,
  CAST(NULL AS FLOAT64) AS revenue
FROM `momovn-prod.BU_FI.FIS_TCST`
WHERE SERVICE_TYPE = 'CLO'
  AND STATUS_CODE IN ('CONTRACT_SIGNED', 'DISBURSED')
  AND DATE_MODIFIED BETWEEN '2025-01-01' AND '2026-02-28'
  AND EXTRACT(MONTH FROM DATE_MODIFIED) IN (1, 2)
GROUP BY 1

UNION ALL

-- Part 2: Revenue by month (use DATE_REQUESTED — Mimir uses DATE_MODIFIED wrongly)
SELECT
  DATE_TRUNC(DATE_REQUESTED, MONTH) AS month,
  CAST(NULL AS INT64) AS contract_count,
  CAST(NULL AS FLOAT64) AS disbursement_amount,
  SUM(REVENUE) AS revenue
FROM `momovn-prod.BU_FI.FIS_TCST`
WHERE SERVICE_TYPE = 'CLO'
  AND DATE_REQUESTED BETWEEN '2025-01-01' AND '2026-02-28'
  AND EXTRACT(MONTH FROM DATE_REQUESTED) IN (1, 2)
GROUP BY 1

ORDER BY month
