-- Batch 18 Q3: CLO lender breakdown Jan 2026
-- FIS_TCST, SERVICE_TYPE='CLO', disbursement by PARTNER_ID

SELECT
  PARTNER_ID,
  COUNT(DISTINCT TICKET_ID)    AS contracts,
  ROUND(SUM(CONTRACT_AMOUNT)/1e9, 1) AS disbursed_B,
  ROUND(AVG(CONTRACT_AMOUNT)/1e6, 1) AS avg_loan_M,
  ROUND(SUM(REVENUE)/1e9, 3)        AS revenue_B
FROM `momovn-prod.BU_FI.FIS_TCST`
WHERE SERVICE_TYPE = 'CLO'
  AND STATUS_CODE IN ('CONTRACT_SIGNED', 'DISBURSED')
  AND DATE_MODIFIED BETWEEN '2026-01-01' AND '2026-01-31'
GROUP BY 1
ORDER BY contracts DESC
