-- Q5: InsurTech Collection-only MAU trend Jul 2025 – Feb 2026
-- Collection = INS_COL_ALL_TRANS, STATUSID = 2 (success)

SELECT
  DATE_TRUNC(TRANS_DATE, MONTH) AS month,
  COUNT(DISTINCT CAST(USER_PAYMENT AS STRING)) AS collection_mau
FROM `momovn-prod.BU_FI.INS_COL_ALL_TRANS`
WHERE STATUSID = 2
  AND TRANS_DATE BETWEEN '2025-07-01' AND '2026-02-28'
GROUP BY 1
ORDER BY 1
