SELECT
  DATE_TRUNC(TRANS_DATE, MONTH) AS month,
  COUNTIF(TYPEID IS NULL OR TYPEID='') AS organic,
  COUNTIF(TYPEID IS NOT NULL AND TYPEID != '') AS promo,
  COUNT(*) AS total
FROM `momovn-prod.BU_FI.att_fi_ins_nl_ver2`
WHERE CC_STATUS='SUCCESS'
  AND SP='Vehicle Ins'
  AND TRANS_DATE BETWEEN '2026-02-01' AND '2026-02-28'
GROUP BY 1
