-- D5: Vay Nhanh Jan 2026 disbursement by LENDER_ID
-- Date: DISBURSED_DATE, no STATUS filter (DISBURSED + LIQUIDATED both count)

SELECT
  LENDER_ID,
  COUNT(*) AS loan_count,
  SUM(DISBURSED_AMOUNT) AS total_disbursed,
  ROUND(AVG(DISBURSED_AMOUNT)) AS avg_loan,
  ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) AS pct_count,
  ROUND(SUM(DISBURSED_AMOUNT) * 100.0 / SUM(SUM(DISBURSED_AMOUNT)) OVER (), 1) AS pct_amount
FROM `momovn-prod.BU_FI.BAOTU_VAYNHANH_LOAN_INFO`
WHERE DISBURSED_DATE BETWEEN '2026-01-01' AND '2026-01-31'
GROUP BY LENDER_ID
ORDER BY loan_count DESC;
